### ISSUE TITLE
ocam-calib converter does not work correctly

### ISSUE THREAD

**Issue by somdats** [siposcsaba89/ocam-calib-cpp#3] opened 2022-03-28 08:44 UTC
@siposcsaba89  I have calibrated a fish-eye lens camera with scaramuzza toolbox and now using your functionalities to convert it into MeiModel so that I can use it in OpenCV compatible form. However, the results are vastly different If I undistort an image using the actual Scaramuzza tool compared with the undistorted image after using the converter. I made some modifications to your converter, for instance, Board size and square size so that it matches my pattern.
Any lead would be helpful, I did not understand what exactly num_table _count does
Here is the calib result with scaramuzza
#polynomial coefficients for the DIRECT mapping function (ocam_model.ss in MATLAB). These are used by cam2world

5 -4.754486e+02 0.000000e+00 7.054599e-04 6.083052e-08 1.427329e-10

#polynomial coefficients for the inverse mapping function (ocam_model.invpol in MATLAB). These are used by world2cam

9 755.539213 533.425006 108.907522 92.422761 46.680117 24.788708 15.143199 5.684140 0.846350

#center: "row" and "column", starting from 0 (C convention)

577.703946 983.424044

#affine parameters "c", "d", "e"

1.000194 -0.058458 0.058290

#image size: "height" and "width"

1096 1948

Here is the output from your converter tool
Num tables total: 58
sum trans error in meter: 4.77641,
avg_err: 0.0823519
sum rad error in degree: 1906.89,
avg_err: 32.8773Converted parameters:
K:
[1181.330885702317, 0, 983.4547450854144;
0, 1181.014283407671, 577.8375036140573;
0, 0, 1]
xi:
[1.4793677086057

D:
[-0.2698151761484431, 0.3409557309874347, -2.481265261341467e-05, 2.997549119019755e-05]
rms:0.00109052,
num_total_pts: 4283
The results after undistortion with the converted parameter
![undistorted_perspective_test_conv](https://user-images.githubusercontent.com/4468850/160360493-eb3a9707-f8ce-4cee-8c2f-836a214f8896.jpg)
The result with scaramuzza toolbox
![undistorted_perspective_test_25032022_sc](https://user-images.githubusercontent.com/4468850/160360610-084eacf0-7ead-4d60-bdec-1442f877ab42.jpg)

Original Image

![25032022_new0](https://user-images.githubusercontent.com/4468850/160360690-4ac63e8e-3612-49b3-a9e4-15a6f4cc5ddc.jpg)

**Comment by siposcsaba89** [comment] 2022-03-28 09:09
@somdats The calib converter places num_table _count table virtually in front of the camera calibrated by Scaramuzza algorithm and tries to find the closest mei model which minimizes the reprojection error of the virtual table's corner points projected by the mei model.

Based on the pictures, the mei model could be correct. What is the new camera parameters when undistorting the image? It seems to me, that the fov of the undistorted image by scaramuzza toolbox is greater then the fov used to undistort with the converted model. To increase fov, you should decrease the focal length of the new camera matrix when undistorting.

Did you use `cv::omnidir::undistortImage(distorted, undistorted, K, D, xi, int flags, Knew, new_size)` for undistorting with the converted parameters?

**Comment by somdats** [comment] 2022-03-28 11:47
@siposcsaba89  Thanks for your reply
Yes, I use cv::omnidir::undistortImage(src1, dst, K, d, xi_out, cv::omnidir::RECTIFY_PERSPECTIVE, K, s);
Knew =  K , which is the obtained from scaramuzza to mei conversion

**Comment by siposcsaba89** [comment] 2022-03-28 12:08
@somdats The K matrix obtained from the conversion, if you use it as a perspective camera matrix, corresponds to an approximately 80 degree horizontal fov (`atan2(1948/2.0, 1180) * 180 / 3.141592 * 2.0`) camera, if you want to make the rectified image wider, change the new camera matrix accordingly, for example

```
K= [
500, 0, 983.4547450854144;
0, 500, 577.8375036140573;
0, 0, 1]
```
gives you a ~ 125 degree horizontal fov.

**Comment by somdats** [comment] 2022-03-28 12:42
@siposcsaba89 
Thanks again
I guess it is better to use the 1st coefficient of the polynomial estimated by scaramuzza as fx/fy .  i.e in my case should be 475.0, in that case, it should give me a wider FoV.
and distortion coefficient as given by Mei_ouput "D". Is the Distortion coefficient correct ?

![undistorted_perspective_test_conv_new_updated](https://user-images.githubusercontent.com/4468850/160399844-1089cb97-2c24-423e-badf-02f0acfb5959.jpg)
This is what is I get If I use 
Knew = [475.44, 0, 979.14722;
 0, 475.44, 572.68921;
 0, 0, 1]

But, The undistorted image generated by both models does not match exactly.
 In the scaramuzza undistorted image, the corner of the door is shifted upward resulting in slicing off a portion

**Comment by siposcsaba89** [comment] 2022-03-28 14:28
@somdats No problem :)

I don't know if you can directly relate the polynomial coefficients and focal length. The `cv::omnidir::undistortImage` does create a new image according to the provided new camera matrix from the original image and calibration. The original K and D is what the converter gives you, those belong to the original image, and the new camera matrix belongs to the new image. You can choose the new matrix as you like, for example calculate from the fov you need. 

The converted model is not identical to the original Scaramuzza's, but a very good approximation of it. (Affine parameters are not used by the converter, it is assumed to be identity. When I calibrated fisheye lenses, they were always very close to identity, so when I ported the code to c++ I left them out from the optimization.)

**Comment by somdats** [comment] 2022-03-28 15:24
@siposcsaba89 
Yes, The scaramuzza o/p is not directly compatible with the OpenCV calibration parameter. 
However, If a larger FoV is needed, the focal length should be smaller. The 1st coefficient (a0) of the polynomial estimated from scaramuzza will result in a horizontal FoV of ~128 deg ((atan2(1948/2.0, 468.04) * 180 / 3.141592 * 2.0).
I realized that the affine parameter is missing in your conversion, I have added it since in my case the parameters are not close to an identity 
The images as earlier provided actually have a rotation around a pivot point after approximation from the scaramuzza, which is unusual.

**Comment by siposcsaba89** [comment] 2022-03-29 05:58
@somdats I just checked the Scaramuzza's toolbox undistort function and if I understand correctly, it chooses the new principal point to be the exact center of the rectified image, and the focal length to be `image_width / fc`, default value for fc is 5. So based on this information the indentical new camera matrix would be:

```
K_new = [
     img_width/fc, 0, img_width/2,
     0, img_width/fc, img_height/2,
     0, 0, 1]
```

So for example in your case, with fc = 5

```
K_new = [
     389.6, 0, 974,
     0, 389.6, 548,
     0, 0, 1]
```

The rotation can be caused by the choosing of the new camera's principal point.

**Comment by somdats** [comment] 2022-03-29 11:42
@siposcsaba89  
Thanks for pointing out.
The factor fc =5, would be overkill, but yes can be adjusted. The optimized result could be using the first coefficient of the polynomial as the fx/fy which in my case is the value with fc =~4.16.
Few question , does the dimension of the board (10,7) and size (0.15,0.15) default value in your code impacts the estimation? for instance, for me, the board dimension could be (7,5) and square size ( 35mm, 35mm). As I understand, it is just about the world coordinates of the corner points 
How can I improve the approximation of the MeiModel from the scaramuzza using your converter? Does the num_table_count could be tuned to performance optimization?

**Comment by siposcsaba89** [comment] 2022-03-29 12:03
@somdats 
You can play with the board size and dimension, of course, there could be some parameters which are better than what I found, but I converted multiple models and it was good enough for me. 

Yes, you can tune the num table count parameter for performance, I am sure that it is not optimal now, I chose a number which was acceptable for me, performance was not an issue, because I needed to convert the models only once. 

Now the table positions and orientations are randomly selected uniformly. Maybe you can improve the performance and even the quality of the conversion by choosing the virtual table positions and orientations a little bit smarter :). I think with carefully chosen table positions 10-15 table should be enough.

**Comment by siposcsaba89** [comment] 2022-03-30 15:31
@somdats 
Do you have any further question regarding this topic, or can I close this issue?

**Comment by somdats** [comment] 2022-03-31 06:42
> @somdats Do you have any further question regarding this topic, or can I close this issue?

Yes, Please go ahead

**Comment by somdats** [comment] 2022-03-31 06:43
@siposcsaba89 
Hi,
The parameter tuning especially, num table count did not have any impact .
You can close the issue

**Closed as completed** 2022-03-31 08:02 UTC
